/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crss;

/**
 *
 * @author BMK5282
 */
public class crssGui extends javax.swing.JFrame {

    /**
     * Creates new form crssGui
     */
    public crssGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        dsplyBtn = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        addStu = new javax.swing.JButton();
        addCrs = new javax.swing.JButton();
        addRm = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        addStuPane2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        stuList2 = new javax.swing.JList<>();
        frstName2 = new javax.swing.JTextField();
        first2 = new javax.swing.JLabel();
        last2 = new javax.swing.JLabel();
        lastName2 = new javax.swing.JTextField();
        phone2 = new javax.swing.JLabel();
        phoneNum2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addCrsPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addCrsList = new javax.swing.JList<>();
        crsName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        crsRm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        addCrsStuList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        addStuCrsBtn = new javax.swing.JButton();
        addCrsBtn = new javax.swing.JButton();
        crsTime = new javax.swing.JComboBox<>();
        addRmPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rmNumber = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        addRmList = new javax.swing.JList<>();
        addRmBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        addRmCrsList = new javax.swing.JList<>();
        addCrsRmBtn = new javax.swing.JButton();
        delPanel = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        delStu = new javax.swing.JButton();
        delCrs = new javax.swing.JButton();
        delRm = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        delStuPane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        delStuList = new javax.swing.JList<>();
        delStuBtn = new javax.swing.JButton();
        delCrsPane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        delCrsList = new javax.swing.JList<>();
        delCrsBtn = new javax.swing.JButton();
        delRmPane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        delRmList = new javax.swing.JList<>();
        delRmBtn = new javax.swing.JButton();
        dsplyPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        title.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        title.setText("Course Registration and Scheduling System");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");

        dsplyBtn.setText("Display");
        dsplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsplyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout initPanelLayout = new javax.swing.GroupLayout(initPanel);
        initPanel.setLayout(initPanelLayout);
        initPanelLayout.setHorizontalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dsplyBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        initPanelLayout.setVerticalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(delBtn)
                .addGap(18, 18, 18)
                .addComponent(dsplyBtn)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        getContentPane().add(initPanel, "card2");

        addStu.setText("Add Student");
        addStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuActionPerformed(evt);
            }
        });

        addCrs.setText("Add Course");
        addCrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCrsActionPerformed(evt);
            }
        });

        addRm.setText("Add Room");

        title1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        title1.setText("Course Registration and Scheduling System");

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        stuList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(stuList2);

        first2.setText("First Name");

        last2.setText("Last Name");

        phone2.setText("Phone Number");

        jButton1.setText("Add Student");

        javax.swing.GroupLayout addStuPane2Layout = new javax.swing.GroupLayout(addStuPane2);
        addStuPane2.setLayout(addStuPane2Layout);
        addStuPane2Layout.setHorizontalGroup(
            addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStuPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frstName2)
                    .addComponent(lastName2)
                    .addComponent(phoneNum2)
                    .addGroup(addStuPane2Layout.createSequentialGroup()
                        .addGap(0, 80, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(addStuPane2Layout.createSequentialGroup()
                        .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first2)
                            .addComponent(last2)
                            .addComponent(phone2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addStuPane2Layout.setVerticalGroup(
            addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStuPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStuPane2Layout.createSequentialGroup()
                        .addComponent(first2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frstName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(last2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phone2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jLayeredPane2.add(addStuPane2, "card6");

        jLabel1.setText("Course Name");

        addCrsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(addCrsList);

        jLabel2.setText("Course Room");

        jLabel3.setText("Course Time");

        addCrsStuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(addCrsStuList);

        jLabel4.setText("Student List");

        addStuCrsBtn.setText("Add Student to Course");

        addCrsBtn.setText("Add Course");

        crsTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addCrsPaneLayout = new javax.swing.GroupLayout(addCrsPane);
        addCrsPane.setLayout(addCrsPaneLayout);
        addCrsPaneLayout.setHorizontalGroup(
            addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCrsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crsName)
                    .addComponent(crsRm)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCrsPaneLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(addStuCrsBtn))
                    .addGroup(addCrsPaneLayout.createSequentialGroup()
                        .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(addCrsBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(crsTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        addCrsPaneLayout.setVerticalGroup(
            addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCrsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addCrsPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crsRm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crsTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addCrsPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addCrsBtn)
                        .addGap(53, 53, 53)
                        .addComponent(addStuCrsBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addCrsPaneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLayeredPane2.add(addCrsPane, "card3");

        jLabel5.setText("Room Number");

        addRmList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(addRmList);

        addRmBtn.setText("Add Room");
        addRmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRmBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Room List");

        jLabel7.setText("Course List");

        addRmCrsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(addRmCrsList);

        addCrsRmBtn.setText("Add Course to Room");

        javax.swing.GroupLayout addRmPaneLayout = new javax.swing.GroupLayout(addRmPane);
        addRmPane.setLayout(addRmPaneLayout);
        addRmPaneLayout.setHorizontalGroup(
            addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRmPaneLayout.createSequentialGroup()
                .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRmPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rmNumber))
                            .addComponent(addRmBtn))
                        .addGap(11, 11, 11)
                        .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRmPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCrsRmBtn)))
                .addContainerGap())
        );
        addRmPaneLayout.setVerticalGroup(
            addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addRmPaneLayout.createSequentialGroup()
                        .addComponent(rmNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addRmBtn))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCrsRmBtn)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredPane2.add(addRmPane, "card4");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title1)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addStu)
                            .addComponent(addCrs, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(title1)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addStu)
                        .addGap(18, 18, 18)
                        .addComponent(addCrs)
                        .addGap(18, 18, 18)
                        .addComponent(addRm))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(addPanel, "card3");

        title2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        title2.setText("Course Registration and Scheduling System");

        delStu.setText("Delete Student");

        delCrs.setText("Delete Course");

        delRm.setText("Delete Room");

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jLabel8.setText("Student List");

        delStuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(delStuList);

        delStuBtn.setText("Delete Student");
        delStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delStuPaneLayout = new javax.swing.GroupLayout(delStuPane);
        delStuPane.setLayout(delStuPaneLayout);
        delStuPaneLayout.setHorizontalGroup(
            delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delStuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delStuPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delStuBtn))
                    .addComponent(jLabel8))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        delStuPaneLayout.setVerticalGroup(
            delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delStuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delStuBtn)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(delStuPane, "card2");

        jLabel9.setText("Course List");

        delCrsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(delCrsList);

        delCrsBtn.setText("Delete Course");

        javax.swing.GroupLayout delCrsPaneLayout = new javax.swing.GroupLayout(delCrsPane);
        delCrsPane.setLayout(delCrsPaneLayout);
        delCrsPaneLayout.setHorizontalGroup(
            delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delCrsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(delCrsPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delCrsBtn)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        delCrsPaneLayout.setVerticalGroup(
            delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delCrsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(delCrsPaneLayout.createSequentialGroup()
                        .addComponent(delCrsBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLayeredPane1.add(delCrsPane, "card3");

        jLabel10.setText("Room List");

        delRmList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(delRmList);

        delRmBtn.setText("Delete Room");

        javax.swing.GroupLayout delRmPaneLayout = new javax.swing.GroupLayout(delRmPane);
        delRmPane.setLayout(delRmPaneLayout);
        delRmPaneLayout.setHorizontalGroup(
            delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delRmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(delRmPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delRmBtn)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        delRmPaneLayout.setVerticalGroup(
            delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delRmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(delRmPaneLayout.createSequentialGroup()
                        .addComponent(delRmBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLayeredPane1.add(delRmPane, "card4");

        javax.swing.GroupLayout delPanelLayout = new javax.swing.GroupLayout(delPanel);
        delPanel.setLayout(delPanelLayout);
        delPanelLayout.setHorizontalGroup(
            delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delPanelLayout.createSequentialGroup()
                        .addComponent(title2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(delPanelLayout.createSequentialGroup()
                        .addGroup(delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(delCrs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delRm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delStu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1)))
                .addContainerGap())
        );
        delPanelLayout.setVerticalGroup(
            delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(delStu)
                        .addGap(26, 26, 26)
                        .addComponent(delCrs)
                        .addGap(32, 32, 32)
                        .addComponent(delRm)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );

        getContentPane().add(delPanel, "card4");

        javax.swing.GroupLayout dsplyPaneLayout = new javax.swing.GroupLayout(dsplyPane);
        dsplyPane.setLayout(dsplyPaneLayout);
        dsplyPaneLayout.setHorizontalGroup(
            dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        dsplyPaneLayout.setVerticalGroup(
            dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        getContentPane().add(dsplyPane, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dsplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsplyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsplyBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void addCrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCrsActionPerformed

    private void addRmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRmBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRmBtnActionPerformed

    private void delStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delStuBtnActionPerformed

    private void addStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crssGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addCrs;
    private javax.swing.JButton addCrsBtn;
    private javax.swing.JList<String> addCrsList;
    private javax.swing.JPanel addCrsPane;
    private javax.swing.JButton addCrsRmBtn;
    private javax.swing.JList<String> addCrsStuList;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton addRm;
    private javax.swing.JButton addRmBtn;
    private javax.swing.JList<String> addRmCrsList;
    private javax.swing.JList<String> addRmList;
    private javax.swing.JPanel addRmPane;
    private javax.swing.JButton addStu;
    private javax.swing.JButton addStuCrsBtn;
    private javax.swing.JPanel addStuPane;
    private javax.swing.JPanel addStuPane1;
    private javax.swing.JPanel addStuPane2;
    private javax.swing.JTextField crsName;
    private javax.swing.JTextField crsRm;
    private javax.swing.JComboBox<String> crsTime;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton delCrs;
    private javax.swing.JButton delCrsBtn;
    private javax.swing.JList<String> delCrsList;
    private javax.swing.JPanel delCrsPane;
    private javax.swing.JPanel delPanel;
    private javax.swing.JButton delRm;
    private javax.swing.JButton delRmBtn;
    private javax.swing.JList<String> delRmList;
    private javax.swing.JPanel delRmPane;
    private javax.swing.JButton delStu;
    private javax.swing.JButton delStuBtn;
    private javax.swing.JList<String> delStuList;
    private javax.swing.JPanel delStuPane;
    private javax.swing.JButton dsplyBtn;
    private javax.swing.JPanel dsplyPane;
    private javax.swing.JLabel first;
    private javax.swing.JLabel first1;
    private javax.swing.JLabel first2;
    private javax.swing.JTextField frstName;
    private javax.swing.JTextField frstName1;
    private javax.swing.JTextField frstName2;
    private javax.swing.JPanel initPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel last;
    private javax.swing.JLabel last1;
    private javax.swing.JLabel last2;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField lastName1;
    private javax.swing.JTextField lastName2;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phone2;
    private javax.swing.JTextField phoneNum;
    private javax.swing.JTextField phoneNum1;
    private javax.swing.JTextField phoneNum2;
    private javax.swing.JTextField rmNumber;
    private javax.swing.JList<String> stuList;
    private javax.swing.JList<String> stuList1;
    private javax.swing.JList<String> stuList2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
