/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crss;

import crss.Course;
import crss.Room;
import crss.Student;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author BMK5282
 */
public class crssGui extends javax.swing.JFrame {

    /**
     * Creates new form crssGui
     */
    
    static ArrayList<Student> stud = new ArrayList();
    static ArrayList<Course> crs = new ArrayList();
    static ArrayList<Room> rm = new ArrayList();
    static ArrayList<Student> studInCrs = new ArrayList();
    
    public crssGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        dsplyBtn = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        addStu = new javax.swing.JButton();
        addCrs = new javax.swing.JButton();
        addRm = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();
        addStuffPane = new javax.swing.JLayeredPane();
        addStuPane2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addStuFirst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addStuLast = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addStuPhone = new javax.swing.JTextField();
        addStuBtn = new javax.swing.JButton();
        addStuOutputBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addStuList = new javax.swing.JTextArea();
        addCrsPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addCrsName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addCrsTime = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addCrsStuBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        addCrsStuList = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        addCrsList = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        addCrsRmList = new javax.swing.JComboBox<String>();
        addCrsRefresh = new javax.swing.JToggleButton();
        addRmPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addRmNum = new javax.swing.JTextField();
        addRmBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        addRmCrsBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        addRmList = new javax.swing.JTextArea();
        addRmCrsList = new javax.swing.JComboBox();
        mainMenuBtn1 = new javax.swing.JButton();
        delPanel = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        delStu = new javax.swing.JButton();
        mainMenuBtn2 = new javax.swing.JButton();
        delCrs = new javax.swing.JButton();
        delRm = new javax.swing.JButton();
        delStuffPane = new javax.swing.JLayeredPane();
        delStuPane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        delStuList = new javax.swing.JList<String>();
        delStuBtn = new javax.swing.JButton();
        delStuOutputBtn = new javax.swing.JButton();
        delCrsPane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        delCrsList = new javax.swing.JList<String>();
        delCrsBtn = new javax.swing.JButton();
        delCrsOutputBtn = new javax.swing.JButton();
        delRmPane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        delRmList = new javax.swing.JList<String>();
        delRmBtn = new javax.swing.JButton();
        delRmOutputBtn = new javax.swing.JButton();
        dsplyPane = new javax.swing.JPanel();
        dsplyStuBtn = new javax.swing.JButton();
        dsplyCrsBtn = new javax.swing.JButton();
        dsplyRmBtn = new javax.swing.JButton();
        dsplySelectMenu = new javax.swing.JLayeredPane();
        stuDisplay = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dsplyFirstName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dsplyLastName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dsplyPhoneNum = new javax.swing.JTextField();
        dsplyStuEnter = new javax.swing.JButton();
        rmDisplay = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        dsplyRmNum = new javax.swing.JTextField();
        dsplyRmEnter = new javax.swing.JButton();
        crseDisplay = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dsplyCrseName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        dsplyCrseTime = new javax.swing.JComboBox<String>();
        dsplyListPane = new javax.swing.JLayeredPane();
        dsplyStuListPane = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        dsplyStuList = new javax.swing.JList<String>();
        dsplyStuOutputBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        dsplyCrsListPane = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        dsplyCrseList = new javax.swing.JList<String>();
        dsplyCrsOutputBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        dsplyRmListPane = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        dsplyRmList = new javax.swing.JList<String>();
        dsplyRmOutputBtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        mainMenuBtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        title.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        title.setText("Course Registration and Scheduling System");

        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addBtnMousePressed(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delBtnMousePressed(evt);
            }
        });

        dsplyBtn.setText("Display");
        dsplyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsplyBtnMousePressed(evt);
            }
        });
        dsplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsplyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout initPanelLayout = new javax.swing.GroupLayout(initPanel);
        initPanel.setLayout(initPanelLayout);
        initPanelLayout.setHorizontalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dsplyBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        initPanelLayout.setVerticalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(delBtn)
                .addGap(18, 18, 18)
                .addComponent(dsplyBtn)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(initPanel, "card2");

        addStu.setText("Add Student");
        addStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addStuMousePressed(evt);
            }
        });
        addStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuActionPerformed(evt);
            }
        });

        addCrs.setText("Add Course");
        addCrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCrsMousePressed(evt);
            }
        });
        addCrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCrsActionPerformed(evt);
            }
        });

        addRm.setText("Add Room");
        addRm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addRmMousePressed(evt);
            }
        });

        title1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        title1.setText("Course Registration and Scheduling System");

        addStuffPane.setLayout(new java.awt.CardLayout());

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Phone Number");

        addStuBtn.setText("Add Student");
        addStuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addStuBtnMousePressed(evt);
            }
        });

        addStuOutputBtn.setText("Output list to text file");

        jLabel20.setText("Student List");

        addStuList.setEditable(false);
        addStuList.setColumns(20);
        addStuList.setRows(5);
        addStuList.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(addStuList);

        javax.swing.GroupLayout addStuPane2Layout = new javax.swing.GroupLayout(addStuPane2);
        addStuPane2.setLayout(addStuPane2Layout);
        addStuPane2Layout.setHorizontalGroup(
            addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStuPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(addStuFirst)
                        .addComponent(jLabel2)
                        .addComponent(addStuLast)
                        .addComponent(jLabel3)
                        .addComponent(addStuPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(addStuBtn)
                    .addComponent(addStuOutputBtn))
                .addGap(18, 18, 18)
                .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStuPane2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap())
        );
        addStuPane2Layout.setVerticalGroup(
            addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStuPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addStuPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStuPane2Layout.createSequentialGroup()
                        .addComponent(addStuFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStuLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStuPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addStuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(addStuOutputBtn))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        addStuffPane.add(addStuPane2, "card2");

        jLabel4.setText("Course Name");

        jLabel5.setText("Course Time");

        addCrsTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "9:00am", "10:00am", "11:00am", "12:00pm", "1:00pm", "2:00pm", "3:00pm", "4:00pm", "5:00pm" }));

        jButton1.setText("Add Course");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Course List");

        addCrsStuBtn.setText("Add Student to Course");
        addCrsStuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCrsStuBtnMousePressed(evt);
            }
        });

        jLabel19.setText("Student List");

        addCrsStuList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));

        addCrsList.setEditable(false);
        addCrsList.setColumns(20);
        addCrsList.setRows(5);
        jScrollPane2.setViewportView(addCrsList);

        jLabel24.setText("Room List");

        addCrsRmList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));

        addCrsRefresh.setText("Refresh");
        addCrsRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCrsRefreshMousePressed(evt);
            }
        });

        javax.swing.GroupLayout addCrsPaneLayout = new javax.swing.GroupLayout(addCrsPane);
        addCrsPane.setLayout(addCrsPaneLayout);
        addCrsPaneLayout.setHorizontalGroup(
            addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCrsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCrsPaneLayout.createSequentialGroup()
                        .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCrsPaneLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addCrsRefresh))
                            .addComponent(jLabel19)
                            .addComponent(addCrsStuBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(addCrsPaneLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCrsPaneLayout.createSequentialGroup()
                        .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addCrsRmList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addCrsPaneLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(addCrsName)
                            .addComponent(addCrsTime, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(addCrsStuList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        addCrsPaneLayout.setVerticalGroup(
            addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCrsPaneLayout.createSequentialGroup()
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCrsPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addComponent(addCrsRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCrsPaneLayout.createSequentialGroup()
                        .addComponent(addCrsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCrsTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCrsRmList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCrsStuList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCrsStuBtn))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        addStuffPane.add(addCrsPane, "card3");

        jLabel7.setText("Room Number");

        addRmBtn.setText("Add Room");
        addRmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addRmBtnMousePressed(evt);
            }
        });

        jLabel17.setText("Course List");

        addRmCrsBtn.setText("Add Course to Room");

        jLabel18.setText("Room List");

        addRmList.setColumns(20);
        addRmList.setRows(5);
        jScrollPane3.setViewportView(addRmList);

        addRmCrsList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addRmPaneLayout = new javax.swing.GroupLayout(addRmPane);
        addRmPane.setLayout(addRmPaneLayout);
        addRmPaneLayout.setHorizontalGroup(
            addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17)
                    .addComponent(addRmCrsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addRmNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRmBtn)
                    .addComponent(addRmCrsList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRmPaneLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addRmPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        addRmPaneLayout.setVerticalGroup(
            addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRmPaneLayout.createSequentialGroup()
                        .addComponent(addRmNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRmBtn)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRmCrsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRmCrsBtn)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        addStuffPane.add(addRmPane, "card4");

        mainMenuBtn1.setText("Main Menu");
        mainMenuBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainMenuBtn1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(title1)
                        .addContainerGap())
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addStu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addRm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainMenuBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(addCrs, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStuffPane))))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(addStu)
                        .addGap(18, 18, 18)
                        .addComponent(addCrs)
                        .addGap(18, 18, 18)
                        .addComponent(addRm)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuBtn1)
                        .addContainerGap())
                    .addComponent(addStuffPane)))
        );

        getContentPane().add(addPanel, "card3");

        title2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        title2.setText("Course Registration and Scheduling System");

        delStu.setText("Delete Student");
        delStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delStuMousePressed(evt);
            }
        });

        mainMenuBtn2.setText("Main Menu");
        mainMenuBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainMenuBtn2MousePressed(evt);
            }
        });

        delCrs.setText("Delete Course");
        delCrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delCrsMousePressed(evt);
            }
        });

        delRm.setText("Delete Room");
        delRm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delRmMousePressed(evt);
            }
        });

        delStuffPane.setLayout(new java.awt.CardLayout());

        jLabel8.setText("Student List");

        delStuList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(delStuList);

        delStuBtn.setText("Delete Student");
        delStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStuBtnActionPerformed(evt);
            }
        });

        delStuOutputBtn.setText("Output List to Text File");

        javax.swing.GroupLayout delStuPaneLayout = new javax.swing.GroupLayout(delStuPane);
        delStuPane.setLayout(delStuPaneLayout);
        delStuPaneLayout.setHorizontalGroup(
            delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delStuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delStuPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delStuOutputBtn)
                            .addComponent(delStuBtn)))
                    .addComponent(jLabel8))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        delStuPaneLayout.setVerticalGroup(
            delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delStuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delStuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delStuPaneLayout.createSequentialGroup()
                        .addComponent(delStuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delStuOutputBtn))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap())
        );

        delStuffPane.add(delStuPane, "card2");

        jLabel9.setText("Course List");

        delCrsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(delCrsList);

        delCrsBtn.setText("Delete Course");

        delCrsOutputBtn.setText("Output List to Text File");

        javax.swing.GroupLayout delCrsPaneLayout = new javax.swing.GroupLayout(delCrsPane);
        delCrsPane.setLayout(delCrsPaneLayout);
        delCrsPaneLayout.setHorizontalGroup(
            delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delCrsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(delCrsPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delCrsOutputBtn)
                            .addComponent(delCrsBtn))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        delCrsPaneLayout.setVerticalGroup(
            delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delCrsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delCrsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addGroup(delCrsPaneLayout.createSequentialGroup()
                        .addComponent(delCrsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delCrsOutputBtn)))
                .addContainerGap())
        );

        delStuffPane.add(delCrsPane, "card3");

        jLabel10.setText("Room List");

        delRmList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(delRmList);

        delRmBtn.setText("Delete Room");

        delRmOutputBtn.setText("Output List to Text File");

        javax.swing.GroupLayout delRmPaneLayout = new javax.swing.GroupLayout(delRmPane);
        delRmPane.setLayout(delRmPaneLayout);
        delRmPaneLayout.setHorizontalGroup(
            delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delRmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(delRmPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delRmBtn)
                            .addComponent(delRmOutputBtn))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        delRmPaneLayout.setVerticalGroup(
            delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delRmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delRmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addGroup(delRmPaneLayout.createSequentialGroup()
                        .addComponent(delRmBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delRmOutputBtn)))
                .addContainerGap())
        );

        delStuffPane.add(delRmPane, "card4");

        javax.swing.GroupLayout delPanelLayout = new javax.swing.GroupLayout(delPanel);
        delPanel.setLayout(delPanelLayout);
        delPanelLayout.setHorizontalGroup(
            delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delPanelLayout.createSequentialGroup()
                        .addComponent(title2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(delPanelLayout.createSequentialGroup()
                        .addGroup(delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(delCrs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delRm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delStu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(mainMenuBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delStuffPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        delPanelLayout.setVerticalGroup(
            delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delPanelLayout.createSequentialGroup()
                        .addComponent(delStu)
                        .addGap(18, 18, 18)
                        .addComponent(delCrs)
                        .addGap(18, 18, 18)
                        .addComponent(delRm)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuBtn2)
                        .addContainerGap())
                    .addComponent(delStuffPane)))
        );

        getContentPane().add(delPanel, "card4");

        dsplyStuBtn.setText("Display Student");
        dsplyStuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsplyStuBtnMousePressed(evt);
            }
        });

        dsplyCrsBtn.setText("Display Course");
        dsplyCrsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsplyCrsBtnMousePressed(evt);
            }
        });

        dsplyRmBtn.setText("Display Room");
        dsplyRmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsplyRmBtnMousePressed(evt);
            }
        });

        dsplySelectMenu.setLayout(new java.awt.CardLayout());

        jLabel11.setText("First Name");

        jLabel12.setText("Last Name");

        jLabel13.setText("Phone Number");

        dsplyStuEnter.setText("Enter");

        javax.swing.GroupLayout stuDisplayLayout = new javax.swing.GroupLayout(stuDisplay);
        stuDisplay.setLayout(stuDisplayLayout);
        stuDisplayLayout.setHorizontalGroup(
            stuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(dsplyFirstName)
                    .addComponent(jLabel12)
                    .addComponent(dsplyLastName)
                    .addComponent(jLabel13)
                    .addComponent(dsplyPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(dsplyStuEnter)
                .addContainerGap())
        );
        stuDisplayLayout.setVerticalGroup(
            stuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stuDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dsplyStuEnter)
                .addContainerGap())
        );

        dsplySelectMenu.add(stuDisplay, "card2");

        jLabel14.setText("Room Number");

        dsplyRmEnter.setText("Enter");

        javax.swing.GroupLayout rmDisplayLayout = new javax.swing.GroupLayout(rmDisplay);
        rmDisplay.setLayout(rmDisplayLayout);
        rmDisplayLayout.setHorizontalGroup(
            rmDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rmDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rmDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(dsplyRmNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dsplyRmEnter))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        rmDisplayLayout.setVerticalGroup(
            rmDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rmDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyRmNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(dsplyRmEnter)
                .addContainerGap())
        );

        dsplySelectMenu.add(rmDisplay, "card3");

        jLabel15.setText("Course Name");

        jButton5.setText("Enter");

        jLabel16.setText("Course Time");

        dsplyCrseTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout crseDisplayLayout = new javax.swing.GroupLayout(crseDisplay);
        crseDisplay.setLayout(crseDisplayLayout);
        crseDisplayLayout.setHorizontalGroup(
            crseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crseDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(dsplyCrseName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(dsplyCrseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        crseDisplayLayout.setVerticalGroup(
            crseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crseDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyCrseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyCrseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        dsplySelectMenu.add(crseDisplay, "card4");

        dsplyListPane.setLayout(new java.awt.CardLayout());

        dsplyStuList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(dsplyStuList);

        dsplyStuOutputBtn.setText("Output list to text file");

        jLabel21.setText("Student List");

        javax.swing.GroupLayout dsplyStuListPaneLayout = new javax.swing.GroupLayout(dsplyStuListPane);
        dsplyStuListPane.setLayout(dsplyStuListPaneLayout);
        dsplyStuListPaneLayout.setHorizontalGroup(
            dsplyStuListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsplyStuListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dsplyStuListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsplyStuListPaneLayout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addComponent(dsplyStuOutputBtn))
                    .addGroup(dsplyStuListPaneLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dsplyStuListPaneLayout.setVerticalGroup(
            dsplyStuListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsplyStuListPaneLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyStuOutputBtn)
                .addContainerGap())
        );

        dsplyListPane.add(dsplyStuListPane, "card2");

        dsplyCrseList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(dsplyCrseList);

        dsplyCrsOutputBtn.setText("Output list to text file");

        jLabel23.setText("Course List");

        javax.swing.GroupLayout dsplyCrsListPaneLayout = new javax.swing.GroupLayout(dsplyCrsListPane);
        dsplyCrsListPane.setLayout(dsplyCrsListPaneLayout);
        dsplyCrsListPaneLayout.setHorizontalGroup(
            dsplyCrsListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsplyCrsListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dsplyCrsListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsplyCrsListPaneLayout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addComponent(dsplyCrsOutputBtn))
                    .addGroup(dsplyCrsListPaneLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dsplyCrsListPaneLayout.setVerticalGroup(
            dsplyCrsListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsplyCrsListPaneLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyCrsOutputBtn)
                .addContainerGap())
        );

        dsplyListPane.add(dsplyCrsListPane, "card3");

        dsplyRmList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(dsplyRmList);

        dsplyRmOutputBtn.setText("Output list to text file");

        jLabel22.setText("Room List");

        javax.swing.GroupLayout dsplyRmListPaneLayout = new javax.swing.GroupLayout(dsplyRmListPane);
        dsplyRmListPane.setLayout(dsplyRmListPaneLayout);
        dsplyRmListPaneLayout.setHorizontalGroup(
            dsplyRmListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsplyRmListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dsplyRmListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsplyRmListPaneLayout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addComponent(dsplyRmOutputBtn))
                    .addGroup(dsplyRmListPaneLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dsplyRmListPaneLayout.setVerticalGroup(
            dsplyRmListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsplyRmListPaneLayout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsplyRmOutputBtn)
                .addContainerGap())
        );

        dsplyListPane.add(dsplyRmListPane, "card4");

        title3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        title3.setText("Course Registration and Scheduling System");

        mainMenuBtn3.setText("Main Menu");
        mainMenuBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainMenuBtn3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout dsplyPaneLayout = new javax.swing.GroupLayout(dsplyPane);
        dsplyPane.setLayout(dsplyPaneLayout);
        dsplyPaneLayout.setHorizontalGroup(
            dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsplyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dsplyPaneLayout.createSequentialGroup()
                        .addComponent(title3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dsplyPaneLayout.createSequentialGroup()
                        .addGroup(dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dsplyPaneLayout.createSequentialGroup()
                                .addGroup(dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dsplyStuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dsplyCrsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dsplyRmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainMenuBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(dsplySelectMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dsplyListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        dsplyPaneLayout.setVerticalGroup(
            dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsplyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dsplyPaneLayout.createSequentialGroup()
                        .addGroup(dsplyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dsplyStuBtn)
                            .addComponent(mainMenuBtn3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dsplyCrsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dsplyRmBtn)
                        .addGap(9, 9, 9)
                        .addComponent(dsplySelectMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dsplyListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(dsplyPane, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dsplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsplyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsplyBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void addCrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCrsActionPerformed

    private void delStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delStuBtnActionPerformed

    private void addStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStuActionPerformed

    private void addBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMousePressed
        // TODO add your handling code here:
        addPanel.setVisible(true);
        delPanel.setVisible(false);
        dsplyPane.setVisible(false);
        initPanel.setVisible(false);
        addStuffPane.setVisible(false);
    }//GEN-LAST:event_addBtnMousePressed

    private void delBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMousePressed
        // TODO add your handling code here:
        delPanel.setVisible(true);
        addPanel.setVisible(false);
        dsplyPane.setVisible(false);
        initPanel.setVisible(false);
        delStuPane.setVisible(false);
    }//GEN-LAST:event_delBtnMousePressed

    private void dsplyBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsplyBtnMousePressed
        // TODO add your handling code here:
        dsplyPane.setVisible(true);
        addPanel.setVisible(false);
        delPanel.setVisible(false);
        initPanel.setVisible(false);
        dsplySelectMenu.setVisible(false);
        dsplyListPane.setVisible(false);
    }//GEN-LAST:event_dsplyBtnMousePressed

    private void addStuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStuMousePressed
        // TODO add your handling code here:
        addStuPane2.setVisible(true);
        addCrsPane.setVisible(false);
        addRmPane.setVisible(false);
        addStuffPane.setVisible(true);
    }//GEN-LAST:event_addStuMousePressed

    private void addCrsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCrsMousePressed
        // TODO add your handling code here:
        addCrsPane.setVisible(true);
        addStuPane2.setVisible(false);
        addRmPane.setVisible(false);
        addStuffPane.setVisible(true);
        
        for (Student i : stud) {
            addCrsStuList.addItem("First Name: " + i.getFirst() + "\tLast Name: "
            + i.getLast() + "\tPhone Number: " + i.getPhone() + "\n");
        }
        
        for (Room r : rm) {
            addCrsRmList.addItem("Room Num: " + r.getNum() + "\n");
        }
    }//GEN-LAST:event_addCrsMousePressed

    private void addRmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRmMousePressed
        // TODO add your handling code here:
        addRmPane.setVisible(true);
        addStuPane2.setVisible(false);
        addCrsPane.setVisible(false);
        addStuffPane.setVisible(true);
    }//GEN-LAST:event_addRmMousePressed

    private void mainMenuBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtn1MousePressed
        // TODO add your handling code here:
        initPanel.setVisible(true);
        addRmPane.setVisible(false);
        addStuPane2.setVisible(false);
        addCrsPane.setVisible(false);
        addPanel.setVisible(false);
    }//GEN-LAST:event_mainMenuBtn1MousePressed

    private void mainMenuBtn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtn2MousePressed
        // TODO add your handling code here:
        initPanel.setVisible(true);
        delPanel.setVisible(false);
    }//GEN-LAST:event_mainMenuBtn2MousePressed

    private void delStuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delStuMousePressed
        // TODO add your handling code here:
        delStuPane.setVisible(true);
        delRmPane.setVisible(false);
        delCrsPane.setVisible(false);
    }//GEN-LAST:event_delStuMousePressed

    private void delCrsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delCrsMousePressed
        // TODO add your handling code here:
        delStuPane.setVisible(false);
        delRmPane.setVisible(false);
        delCrsPane.setVisible(true);
    }//GEN-LAST:event_delCrsMousePressed

    private void delRmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delRmMousePressed
        // TODO add your handling code here:
        delStuPane.setVisible(false);
        delRmPane.setVisible(true);
        delCrsPane.setVisible(false);
    }//GEN-LAST:event_delRmMousePressed

    private void mainMenuBtn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtn3MousePressed
        // TODO add your handling code here:
        initPanel.setVisible(true);
        dsplyPane.setVisible(false);
    }//GEN-LAST:event_mainMenuBtn3MousePressed

    private void dsplyStuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsplyStuBtnMousePressed
        // TODO add your handling code here:
        dsplySelectMenu.setVisible(true);
        dsplyListPane.setVisible(true);
        stuDisplay.setVisible(true);
        dsplyStuListPane.setVisible(true);
        crseDisplay.setVisible(false);
        rmDisplay.setVisible(false);
        dsplyCrsListPane.setVisible(false);
        dsplyRmListPane.setVisible(false);
    }//GEN-LAST:event_dsplyStuBtnMousePressed

    private void dsplyCrsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsplyCrsBtnMousePressed
        // TODO add your handling code here:
        dsplySelectMenu.setVisible(true);
        dsplyListPane.setVisible(true);
        stuDisplay.setVisible(false);
        dsplyStuListPane.setVisible(false);
        crseDisplay.setVisible(true);
        rmDisplay.setVisible(false);
        dsplyCrsListPane.setVisible(true);
        dsplyRmListPane.setVisible(false);
    }//GEN-LAST:event_dsplyCrsBtnMousePressed

    private void dsplyRmBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsplyRmBtnMousePressed
        // TODO add your handling code here:
        dsplySelectMenu.setVisible(true);
        dsplyListPane.setVisible(true);
        stuDisplay.setVisible(false);
        dsplyStuListPane.setVisible(false);
        crseDisplay.setVisible(false);
        rmDisplay.setVisible(true);
        dsplyCrsListPane.setVisible(false);
        dsplyRmListPane.setVisible(true);
    }//GEN-LAST:event_dsplyRmBtnMousePressed

    private void addStuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStuBtnMousePressed
        // TODO add your handling code here:
        // vars for inputting
        String firstName = "";
        String lastName = "";
        String phoneNum = "";
        boolean isGood = false;
        // setting the text field to the vars
        firstName = addStuFirst.getText();
        lastName = addStuLast.getText();
        phoneNum = addStuPhone.getText();
        
        // if phone num is not ten display prompt
        if (phoneNum.length() != 10) {
            JOptionPane.showMessageDialog(this, "Not enough digits");
            isGood = false;
        }
        
        // if first and last name exist set isThere to true
        boolean isThere = false;
        if (!stud.isEmpty()) {
            for (Student stu : stud) {
                if (firstName == stu.getFirst()) {
                    if (lastName == stu.getLast()) {
                        if (phoneNum == stu.getPhone()) {
                            isThere = true;
                            break;
                        }
                    }
                }
            }
        }
        
        /* if there show message dialog, if not create new student and reset
        field
        */
        if (isThere == true) {
            JOptionPane.showMessageDialog(this, "Student Already exists");
        }
        else {
            stud.add(new Student(firstName, lastName, phoneNum));
            addStuFirst.setText("");
            addStuLast.setText("");
            addStuPhone.setText("");
        }
        
        // reset field
        addStuFirst.setText("");
        addStuLast.setText("");
        addStuPhone.setText("");
        addStuList.setText("");
        
        // add to jlist
        for (Student stu : stud) {
            addStuList.append("First Name: " + stu.getFirst() + "\tLast Name: " 
            + stu.getLast() + "\tPhone Number: " + stu.getPhone() + "\n");
        }
        addStuList.repaint();
    }//GEN-LAST:event_addStuBtnMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        // vars
        String crsName = "";
        boolean isThere = false;
        boolean isGood = false;
        boolean isFree = false;
        int crsTime = 0;
        Room room = null;
        
        crsName = addCrsName.getText();
        
        for (Course crs : crs) {
            if (crsName == crs.getCName()) {
                isThere = true;
                break;
            }
            else {
                isGood = true;
            }
        }
        switch (addCrsTime.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(this, "Need to select a time");
                break;
            case 1:
                crsTime = 9;
                break;
            case 2:
                crsTime = 10;
                break;
            case 3:
                crsTime = 11;
                break;
            case 4:
                crsTime = 12;
                break;
            case 5:
                crsTime = 1;
                break;
            case 6:
                crsTime = 2;
                break;
            case 7:
                crsTime = 3;
                break;
            case 8:
                crsTime = 4;
                break;
            case 9:
                crsTime = 5;
                break;
        }
        for (Room r : rm) {
            if (!r.getCourse().isEmpty()) {
                ArrayList<Course> c = r.getCourse();
                for (Course crs : c) {
                    if (crs.getCtm() == crsTime) {
                        JOptionPane.showMessageDialog(this, "Time is already taken");
                        isGood = false;
                    }
                    else {
                        isGood = true;
                    }
                }
            }
        }
        
        Room roomSelect = (Room) addCrsRmList.getSelectedItem();
        for (Room i : rm) {
            if (isFree == true) {
                if (addCrsRmList.getSelectedIndex() != 0) {
                    room = rm.get(addCrsRmList.getSelectedIndex() - 1);
                    isGood = true;
                }
                else {
                    JOptionPane.showMessageDialog(this, "Need to select a room");
                    isGood = false;
                }
            }
        }
        
        // checking if student added to course
        if (studInCrs.isEmpty()) {
            
        } else {
            Course course = new Course(crsName, crsTime, room, studInCrs); 
            for (Student i : studInCrs) {
                for (Student j : stud) {
                    if (i == j) {
                        j.addCourse(course);
                    }
                }
                i.addCourse(course);
            }
            crs.add(course);
            room.addCourse(course);
        }

        if (isThere == true) {
            JOptionPane.showMessageDialog(this, "Course Already Exits");
        }
        
        if (isGood == true) {
            // updating the course and room and resetting everything
            Course course = new Course(crsName, crsTime, room);
            crs.add(course);
            room.addCourse(course);
            addCrsName.setText("");
            addCrsTime.setSelectedIndex(0);
            addCrsRmList.setSelectedIndex(0);
            addCrsStuList.setSelectedIndex(0);
            

        }
        else {
            JOptionPane.showMessageDialog(this, "Didn't set something correctly");
        }
        
        for (Course c : crs) {
            addCrsList.append("Course Name: " + c.getCName() + "\tCourse Time: "
            + c.getCtm() + "\tRoom: " + c.getCrm().getNum() + "\n");
        }
        addCrsList.repaint();
    }//GEN-LAST:event_jButton1MousePressed

    private void addCrsStuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCrsStuBtnMousePressed
        // TODO add your handling code here:
        Student stu;
        Student select = (Student) addCrsStuList.getSelectedItem();
        int index = addCrsStuList.getSelectedIndex();
        
        for (Student i : stud) {
            addCrsStuList.addItem("First Name: " + i.getFirst() + "\tLast Name: "
            + i.getLast() + "\tPhone Number: " + i.getPhone() + "\n");
        }
        
        studInCrs.add(stud.get(index - 1));
    }//GEN-LAST:event_addCrsStuBtnMousePressed

    private void addRmBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRmBtnMousePressed
        // TODO add your handling code here:
        int rmNum;
        boolean isGood = true;
        rmNum = Integer.parseInt(addRmNum.getText());
        
        if (!rm.isEmpty()) {
            for (Room i : rm) {
                if (rmNum == i.getNum()) {
                    JOptionPane.showMessageDialog(this, "Room already exists");
                    isGood = false;
                    break;
                }
            }
        }
        
        if (isGood) {
            rm.add(new Room(rmNum));
        }
        
        addRmNum.setText("");
        for (Room r : rm) {
            addRmList.append("Room Number: " + r.getNum() + "\n");
        }
        addRmList.repaint();
    }//GEN-LAST:event_addRmBtnMousePressed

    private void addCrsRefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCrsRefreshMousePressed
        // TODO add your handling code here:
        for (Student i : stud) {
            addCrsStuList.addItem("First Name: " + i.getFirst() + "\tLast Name: "
            + i.getLast() + "\tPhone Number: " + i.getPhone() + "\n");
        }
        
        for (Room r : rm) {
            addCrsRmList.addItem("Room Num: " + r.getNum() + "\n");
        }
    }//GEN-LAST:event_addCrsRefreshMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crssGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crssGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addCrs;
    private javax.swing.JTextArea addCrsList;
    private javax.swing.JTextField addCrsName;
    private javax.swing.JPanel addCrsPane;
    private javax.swing.JToggleButton addCrsRefresh;
    private javax.swing.JComboBox<String> addCrsRmList;
    private javax.swing.JButton addCrsStuBtn;
    private javax.swing.JComboBox<String> addCrsStuList;
    private javax.swing.JComboBox<String> addCrsTime;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton addRm;
    private javax.swing.JButton addRmBtn;
    private javax.swing.JButton addRmCrsBtn;
    private javax.swing.JComboBox addRmCrsList;
    private javax.swing.JTextArea addRmList;
    private javax.swing.JTextField addRmNum;
    private javax.swing.JPanel addRmPane;
    private javax.swing.JButton addStu;
    private javax.swing.JButton addStuBtn;
    private javax.swing.JTextField addStuFirst;
    private javax.swing.JTextField addStuLast;
    private javax.swing.JTextArea addStuList;
    private javax.swing.JButton addStuOutputBtn;
    private javax.swing.JPanel addStuPane2;
    private javax.swing.JTextField addStuPhone;
    private javax.swing.JLayeredPane addStuffPane;
    private javax.swing.JPanel crseDisplay;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton delCrs;
    private javax.swing.JButton delCrsBtn;
    private javax.swing.JList<String> delCrsList;
    private javax.swing.JButton delCrsOutputBtn;
    private javax.swing.JPanel delCrsPane;
    private javax.swing.JPanel delPanel;
    private javax.swing.JButton delRm;
    private javax.swing.JButton delRmBtn;
    private javax.swing.JList<String> delRmList;
    private javax.swing.JButton delRmOutputBtn;
    private javax.swing.JPanel delRmPane;
    private javax.swing.JButton delStu;
    private javax.swing.JButton delStuBtn;
    private javax.swing.JList<String> delStuList;
    private javax.swing.JButton delStuOutputBtn;
    private javax.swing.JPanel delStuPane;
    private javax.swing.JLayeredPane delStuffPane;
    private javax.swing.JButton dsplyBtn;
    private javax.swing.JButton dsplyCrsBtn;
    private javax.swing.JPanel dsplyCrsListPane;
    private javax.swing.JButton dsplyCrsOutputBtn;
    private javax.swing.JList<String> dsplyCrseList;
    private javax.swing.JTextField dsplyCrseName;
    private javax.swing.JComboBox<String> dsplyCrseTime;
    private javax.swing.JTextField dsplyFirstName;
    private javax.swing.JTextField dsplyLastName;
    private javax.swing.JLayeredPane dsplyListPane;
    private javax.swing.JPanel dsplyPane;
    private javax.swing.JTextField dsplyPhoneNum;
    private javax.swing.JButton dsplyRmBtn;
    private javax.swing.JButton dsplyRmEnter;
    private javax.swing.JList<String> dsplyRmList;
    private javax.swing.JPanel dsplyRmListPane;
    private javax.swing.JTextField dsplyRmNum;
    private javax.swing.JButton dsplyRmOutputBtn;
    private javax.swing.JLayeredPane dsplySelectMenu;
    private javax.swing.JButton dsplyStuBtn;
    private javax.swing.JButton dsplyStuEnter;
    private javax.swing.JList<String> dsplyStuList;
    private javax.swing.JPanel dsplyStuListPane;
    private javax.swing.JButton dsplyStuOutputBtn;
    private javax.swing.JPanel initPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton mainMenuBtn1;
    private javax.swing.JButton mainMenuBtn2;
    private javax.swing.JButton mainMenuBtn3;
    private javax.swing.JPanel rmDisplay;
    private javax.swing.JPanel stuDisplay;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables


}
